import { Dimensions, StyleSheet } from "react-native";
import colours from '../../common/constants/styles.json'

const styles = StyleSheet.create({
  container: {
    flexGrow: 1,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  loginScreenInput: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: Dimensions.get('window').height * 0.27,
    padding: 8,
    backgroundColor: 'white',
    borderColor: 'lightgray',
    borderBottomWidth: 0,
    borderWidth: 1,
    gap: 10,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  verifyOTPScreenInput: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
    height: Dimensions.get('screen').height * 0.25,
    padding: 16,
    backgroundColor: 'white',
    borderColor: 'lightgray',
    borderBottomWidth: 0,
    borderWidth: 1,
    gap: 26,
    borderTopLeftRadius: 32,
    borderTopRightRadius: 32,
  },
  mobileInputButtons: {
    // marginBottom: 8,
    // gap: 8,
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  verifyOTPInputButtons: {
    width: '100%',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  mobileNumberContiner: {
    // marginTop: Dimensions.get('screen').height * 0.2,
    width: '100%'
  },
  mobileNumberInput: {
    width: '100%',
    borderBottomWidth: 2,
    borderWidth: 2,
    backgroundColor: 'white',
    borderColor: colours['theme-color'],
    paddingHorizontal: 10,
    paddingVertical: 0,
    borderRadius: 55,
  },
  loginImage: {
    marginTop: 16,
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
  },
  verifyOTPButton: {
    width: '70%',
    margin: 8,
    marginTop: 16,
    padding: 4,
    height: 56,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    gap: 20,
    backgroundColor: colours['theme-color'],
    borderRadius: 32,
    elevation: 1,
  },
  loginButton: {
    width: '60%',
    margin: 8,
    padding: 16,
    height: 64,
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    textAlign: 'center',
    gap: 20,
    backgroundColor: colours['theme-color'],
    borderRadius: 32,
    elevation: 4,
  },
  borderStyleBase: {
    width: 30,
    height: 45
  },
  borderStyleHighLighted: {
    borderColor: "#03DAC6",
  },
  OTPFieldStyle: {
    display: 'flex',
    flexDirection: 'row',
    justifyContent: 'center',
    alignItems: 'center',
    width: 50,
    height: 60,
    fontSize: 32,
    borderWidth: 1,
    borderRadius: 8,
    color: 'black',
    marginRight: 20,
    marginLeft: -10,
    marginBottom: 16,
    borderColor: 'hotpink',
    backgroundColor: 'white'
  },

  OTPHightLightStyle: {
    borderColor: 'hotpink',
  },
})

export default styles;